name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.7.0
    - name: Install dependencies
      run: bundle install
      env:
        RAILS_ENV: test
    - name: Run tests
      run: |
        yarn install --check-files
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rspec
      env:
        RAILS_ENV: test